[package]
name = "anthill-di"
version = "0.1.8"
authors = ["Vidrochka <Evgenuy1605@yandex.ru>"]
edition = "2018"
description = "Rust di containers system"
license = "MIT"
homepage = "https://github.com/Vidrochka/anthill-di"
repository = "https://github.com/Vidrochka/anthill-di"
keywords = ["anthill", "di", "anthill-di", "dependency-injection", "build"]

[dependencies]
tokio = { version = "1.12.0", features = ["full"] }